#!/bin/sh
set -e

usermod -a -G www-data root
php /var/www/html/artisan config:cache
php /var/www/html/artisan cache:clear
php /var/www/html/artisan view:clear
php /var/www/html/artisan route:clear
php /var/www/html/artisan queue:restart

# Start app services
service nginx restart
# Don't run queues yet
# /usr/bin/supervisord -n -c /etc/supervisord.conf &
php-fpm
